services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900" #VNC port to watch the browser at localhost:7900
    shm_size: 2g

  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - selenium
    command: python /app/test/test.py
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
